config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :home, only: [:index, :edit, :update] do
    collection do
      post :update_status
      post :add_phone
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @customers = Customer.all.order(:name)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(edit_customer_params)
      redirect_to action: :index
    end
  end

  def update_status
    customer = Customer.find(params[:id])
    customer.update!(in_black_list: false)
    redirect_to action: :index
  end

  def add_phone
    customer = Customer.where(phone: params[:phone])
    customer.update(in_black_list: true)
    redirect_to(home_index_path(list: :black))
  end

  private

  def edit_customer_params
    params.require(:customer).permit(
      :name,
      :phone,
      :description,
      :in_black_list
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_add_by_phone.html.erb
<%= form_tag(add_phone_home_index_path, method: :post) do %>
  Добавить в черный список по номеру телефона:
  <div>
    <input
      type="text"
      name="phone"
      required
      placeholder="номер телефона"
    >
  </div>
  <div>
    <%= submit_tag 'Добавить' %>
  </div>
<% end %>

app/views/home/_black_list.html.erb
<header>
  <h1>Черный список</h1>
</header>

<p>
  <%= link_to(
        'Список клиентов',
        home_index_path(list: :white),
      )
  %>
</p>

<p>
 <%= render 'add_by_phone', customer: @customer %>
</p>

<table>
  <thead>
  <tr>
    <th>id</th>
    <th>Имя</th>
    <th>Телефон</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <% if customer.in_black_list != false %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.name %></td>
        <td><%= customer.phone %></td>
        <td>
          <%= link_to(
                'Редактировать',
                edit_home_path(id: customer.id),
              )
          %>
        </td>
        <td>
          <%= link_to(
                'Исключить',
                update_status_home_index_path(id: customer.id),
                method: :post,
              )
          %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/home/_white_list.erb
<header>
  <h1>Список клиентов</h1>
</header>

<p>
  <%= link_to(
        'Черный список',
        home_index_path(list: :black),
      )
  %>
</p>

<table>
  <thead>
  <tr>
    <th>id</th>
    <th>Имя</th>
    <th>Телефон</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <% if customer.in_black_list == false %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.name %></td>
        <td><%= customer.phone %></td>
        <td>
          <%= link_to(
                'Редактировать',
                edit_home_path(id: customer.id),
              )
          %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/home/edit.html.erb
<h1>Редактирование</h1>

<%= form_for @customer, url: home_path, method: :patch do |form| %>
  <p>
    <%= form.label :name, 'Имя' %>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :phone, 'Телефон' %>
    <%= form.text_field :phone %>
  </p>

  <p>
    <%= form.label :description, 'Описание' %>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :description, 'В черном списке?' %>
    <%= form.check_box :in_black_list %>
  </p>

  <p>
    <%= form.submit 'Сохранить' %>
  </p>
<% end %>

app/views/home/index.html.erb
<% if params[:list] == 'black' %>
  <%= render 'black_list' %>
<% else %>
  <%= render 'white_list' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>